### PR TITLE
Chore/apply reuse software

### PR DESCRIPTION
**Pull request by bufferoverflow**
This PR is based on #63 and does change the license headers according to the https://reuse.software/ guidelines. I would appreciate every feedback on this, especially to talk with the reuse initiative on ways to improve further to simplify and automate license compliance.

### CODE REVIEW

**Comment by hyandell** [comment]
I'm uncomfortable inserting a metadata header into the top of a LICENSE file. That seems to clash with an industry wide expectation that you can have exact file matches for a license file. 

I don't see it in this for example: https://spdx.org/licenses/Apache-2.0.html

**Comment by bufferoverflow** [comment]
@hyandell Yes, the metadata header within the LICENSE file is ugly and there should be another option for this. I was just following the current proposal to get some other impressions on reuse.software. What about the other aspects, such as file headers and it's template `README.md.license`?

**Comment by hyandell** [comment]
Supporting the SPDX Identifier line is good. The (C) isn't defined in law though, and I've seen opinions lean against it.

**Comment by hyandell** [comment]
I'm ambivalent on the README bit. The current repolinter README seems to confuse licensee, so I'd primarily like to see the README and licensee work happily together.

**Comment by bufferoverflow** [comment]
yes, the `(C)` is kind of redundant and also not used by the [DEP-5/copyright](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/) definition.

**Comment by jonasob** [comment]
From someone who's had a hand in the REUSE principles, I agree with you that this is a bit clunky :-) We'd be happy to take input on how to do this in a better way! What we want to achieve is to make it possible for a project to say that "when I use the SPDX identifier FOO, I mean exactly the license in THIS file". Which can also be used as a lint checker: verify that all SPDX identifiers used in a project correspond to a license which is actually included in the project.

If you don't want to touch the license file itself (a sensible option), then you can include the ile header in a file called COPYING.license (assuming the license itself is in COPYING). I think that's a sensible option if you don't have a lot of licenses.

**Comment by bufferoverflow** [comment]
Thanks for the feedback @jonasob , I've addressed your feedback and and added a `LICENSE.license` file. However, the name is not ideal from my perspective.

I also addressed @hyandell input about the `(C)` and removed it.


The build fails now because of `README.md.license` file:

```
AssertionError: expected '(README.md.license) contains blacklisted words in commit 22ff224, and 1 more commits.\n\tBlacklist: Copyright 2017 TODO Group\\. All rights reserved\\.' to match /\(bin\/repolinter\.js\) contains blacklisted words in commit \w{7}, and \d+ more commits\./
```

**Comment by jonasob** [comment]
Agreed @bufferoverflow ! The file name is not ideal. What would you suggest? (`.license` was picked originally since it can contain license information for files in which no license information can be provided, for example certain source code files which can not contain comments.)

**Comment by bufferoverflow** [comment]
What about `LICENSE.spdxid`, `LICENSE.spdx` or the developer friendly variants `.LICENSE.spdx`  `.LICENSE.spdxid`? I guess the spdx file itself will be `package-name.sdpx`, e.g.  `repolinter-0.5.0.spdx`

**Comment by trevmex** [comment]
If you update your branch now, your tests will pass.

Do we have consensus on the filename?

**Comment by bufferoverflow** [comment]
I've removed the `LICENSE.license` file and I would say the changes where some consensus exits are handled.

**Comment by trevmex** [comment]
Perfect. Thanks!

**Pull request merged**
