### PR TITLE
update github-markup to remove python2 dependency

### PR DESCRIPTION
**Pull request by willnorris**
this is technically a breaking change, since it requires having python3 rather than python2 installed if doing anything relating to restructuredText.  However, I suspect it would be a welcome change for many, since the rest of the world has long since moved to python3.

### CODE REVIEW

**Comment by prototypicalpro** [comment]
Could you rebase this PR as well? Thanks!

**Comment by prototypicalpro** [comment]
Actually in addition to that could you update the [Dockerfile](https://github.com/todogroup/repolinter/blob/master/Dockerfile) to Python 3 as well? Before this PR merges I will need to make sure that repolinter-action also works with this change.

**Comment by willnorris** [comment]
> update the [Dockerfile](https://github.com/todogroup/repolinter/blob/master/Dockerfile) to Python 3 as well

ah, yes... good catch.  Updating and testing that now.

**Comment by willnorris** [comment]
done.  rebased (tests now pass) and Dockerfile updated.  I've built the docker image locally and it works as expected.

**Pull request merged**
