### PR TITLE
Move GitHub files to .github folder

### PR DESCRIPTION
**Pull request by jwsloan**
## Motivation

GitHub will pickup the "Community" files from the .github folder.

Moving them there helps keep the root of the directory cleaner.

## Proposed Changes

Move files to .github that make sense to live there.

## Test Plan
Once merged, take a look at the "Community" page in "Insights" to make sure all of these files are still picked up there.

### CODE REVIEW

**Comment by bufferoverflow** [comment]
Issue and pull request templates are the only GitHub specific files to move.

**Comment by hyandell** [comment]
I agree on not moving CONTRIBUTING and CODE_OF_CONDUCT.

I would move the templates & CODEOWNERS as I think they're only valuable at the GitHub level (and in CODEOWNERS case it can decrease community ownership if too front and centre).

**Comment by trevmex** [comment]
Agreed. Can you change this PR to only move the ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE, @jwsloan?

**Comment by jwsloan** [comment]
I understand the concerns with CONTRIBUTING and CODE_OF_CONDUCT. The CAN live in .github, but that doesn't mean they have to. 

I would submit that CODEOWNERS does make sense to move, as it is primarily used by the GitHub system. It is human-readable, but that is not the intent. 

I'll not move it if that is the consensus. I just wanted to make the case that this is a reasonable thing to do.

**Comment by jwsloan** [comment]
When I updated my local copy to match master, `npm audit` told me about some vulnerabilities. I ran `npm audit fix --force` to fix them. That updated `standard`, so I ran `standard --fix` and included that commit. All the tests still pass, so that boy-scouting seemed reasonable.

**Pull request merged**
