### PR TITLE
Update npm and ruby dependencies

### PR DESCRIPTION
**Pull request by JeroenKnoops**
## Motivation

It's always good to keep the dependencies up-to-date.

## Proposed Changes

- Update dependencies in package.json. (added `parse-domain`, and fixed version for `broken_link_checker`).
- Update dependency lock (package-lock.json) files for Npm
- Update dependency lock (Gemfile.lock) files for Ruby

## Test Plan

I've manually installed the same environment as used in the ci workflow file.
I've ran `bundle exec npm test` and all tests passed.

Worked together on this with @brend-smits

### CODE REVIEW

**Comment by JeroenKnoops** [comment]
I've created 5 different logical commits. I can rebase them if you rather see that.

**Comment by JeroenKnoops** [comment]
I will check all failing checks.

**Comment by prototypicalpro** [comment]
I'm not sure if you can view the logs, so if not here is the relevant error:
```
home/runner/work/repolinter/repolinter/node_modules/url-relation/lib/index.js:37
	return evaluateValue(customOptions?.[optionName], ...args) ?? defaultOption;
	                                   ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/runner/work/repolinter/repolinter/node_modules/broken-link-checker/lib-cjs/internal/Link.js:14:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/runner/work/repolinter/repolinter/node_modules/broken-link-checker/lib-cjs/public/HtmlChecker.js:14:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/runner/work/repolinter/repolinter/node_modules/broken-link-checker/lib-cjs/index.js:80:43)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/runner/work/repolinter/repolinter/rules/file-no-broken-links.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Suite.<anonymous> (/home/runner/work/repolinter/repolinter/tests/rules/file_no_broken_links_tests.js:13:31)
    at Object.create (/home/runner/work/repolinter/repolinter/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/home/runner/work/repolinter/repolinter/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Suite.describe (/home/runner/work/repolinter/repolinter/tests/rules/file_no_broken_links_tests.js:11:3)
    at Object.create (/home/runner/work/repolinter/repolinter/node_modules/mocha/lib/interfaces/common.js:148:19)
    at context.describe.context.context (/home/runner/work/repolinter/repolinter/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at Object.<anonymous> (/home/runner/work/repolinter/repolinter/tests/rules/file_no_broken_links_tests.js:10:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.exports.requireOrImport (/home/runner/work/repolinter/repolinter/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/home/runner/work/repolinter/repolinter/node_modules/mocha/lib/esm-utils.js:55:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! Test failed.  See above for more details.
```
I think the error is with a dependency of my fork of `broken-link-checker`, which recently had one of it's dependencies updated to drop node 12 support. I need to reevaluate if that fork can just be replaced with the main package, but in the meantime I've updated it to fix the error so if you run `npm update` again it should work.

**Comment by JeroenKnoops** [comment]
Not needed anymore. Already resolved in #205 
Great work! 🥂

**Pull request closed without merging**
