### PR TITLE
Added a Dockerfile

### PR DESCRIPTION
**Pull request by dmuth**
## Motivation

Docker allows software to be run in "containers".  These containers can be shipped run and run on any machine which has Docker, without having to install additional software.  This is especially useful when the machine may be behind a firewall or other proxy and have difficulty downloading dependencies.

## Proposed Changes

Addition of a `Dockerfile`.

## Test Plan

I'm not sure what a good Test Plan is for a `Dockerfile`. How about:

```
docker built -t repolinter .
docker run -t repolinter --git https://github.com/username/repo.git
```

Let me know if there's anything else you need, and thanks so much for building this app!

-- Doug

### CODE REVIEW

**Comment by jwsloan** [comment]
I was just working on doing this myself this morning. You would need to bring in Ruby to be able to do linquist and licensee checks.

**Comment by dmuth** [comment]
Great minds think alike? :-)

If you can give me a test case (a repo should work) for running a license check, I can add Ruby in on my end and make sure it works!

**Comment by dmuth** [comment]
Do you mean #135?

**Comment by bkeepers** [comment]
Doh, yep.

**Comment by trevmex** [comment]
I think we will go with #135. Thank you for working on this, though!

**Pull request closed without merging**
